### ISSUE TITLE
Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by vlasovilya** [adasq/dropbox-v2-api#1139]
I'm trying to download 737Mb file and getting this: 

```
buffer.js:799
    return this.utf8Slice(start, end);
                ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:799:17)
    at Request.<anonymous> (/home/dev/backup-manager/node_modules/dropbox-v2-api/node_modules/request/request.js:1135:39)
    at Request.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (/home/dev/backup-manager/node_modules/dropbox-v2-api/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

Tried to increase --max-old-space-size but it doesn't help

**Comment by vlasovilya** [comment]
duplicate of https://github.com/adasq/dropbox-v2-api/issues/1121
